lockfiles, minor changes, better info

diff --git a/buildaur b/buildaur
--- a/buildaur
+++ b/buildaur
@@ -44,34 +44,45 @@ netcheck(){
 
 info(){
 	netcheck
-	while [[ $# -gt 1 ]]
+	pkgnames=($@)
+	res="https://aur.archlinux.org/rpc/?v=5&type=multiinfo"
+	counter=0
+	while [[ $counter -lt ${#pkgnames[*]} ]]
 	do
-		key=$2
-		res=$(curl -s 'https://aur.archlinux.org/rpc/?v=5&type=multiinfo&arg[]='$key'')
-		remoteinfo=$(echo $res | cut -d'"' -f30)
-		ver=$(pacman -Q $key 2>/dev/null | cut -d" " -f2 | xargs)
-		if [[ $(echo $res | cut -d'"' -f9) = ":0," ]]
-		then
-			if [[ $all = true ]]
-			then
-				echo "  ${bold}Warning:${normal} $key ist not in the AUR!"
-			else
-				echo "${red}${bold}ERROR:${normal} $key ist not in the AUR!"
-				exit 2
-			fi
-		fi
-		if [[ $ver = "" ]]
+	res=${res}"&arg[]="${pkgnames[$counter]}
+	((counter++))
+	done
+	res=$(curl -s $res)
+	resultcount=$(echo $res | cut -d'"' -f9 | sed -e 's/://g' | sed -e 's/,//g')
+	counter=0
+	while [[ $counter -lt $resultcount ]]
+	do
+		cutted=$(echo $res | cut -d{ -f$(expr $counter + 3))
+		name=$(echo $cutted | cut -d'"' -f6)
+		ver=$(pacman -Q $name 2>/dev/null | cut -d" " -f2 | xargs)
+		remoteinfo=$(echo $cutted | cut -d'"' -f20)
+		if [[ $name = "" ]] || [[ $ver = "" ]]
 		then
 			ver="--- "
 		fi
-		echo "  "$key $(curl -s 'https://aur.archlinux.org/rpc/?v=5&type=multiinfo&arg[]='$key'' | cut -d'"' -f26) "(local: $ver)"
+		echo "  "$name $(echo $cutted | cut -d'"' -f16) "(local: $ver)"
 		if [[ $remoteinfo = "" ]]
 		then
 			echo "     ${bold}Warning:${normal} AUR does not provide information about this package!"
 		else
 			echo "     "$remoteinfo
 		fi
-		shift
+		aurpacs[$counter]=$name
+		((counter++))
+	done
+	localpacs=($(echo ${aurpacs[@]} $@ | tr ' ' '\n' | sort | uniq -u))
+	counter=0
+	while [[ $counter -lt ${#localpacs[*]} ]]
+	do
+		echo "  $(pacman -Q ${localpacs[$counter]})"
+		echo "     ${bold}Warning:${normal} AUR does not provide information about this package!"
+		((count++))
+		((counter++))
 	done
 }
 
@@ -166,18 +177,21 @@ preinst(){
 				echo "${red}${bold}ERROR:${normal} $key ist not in the AUR!"
 				exit 1
 			fi
+			if [[ $(pacman -Qq $key) = $key ]]
+			then
 			if [[ $ver = "" ]]
-			then
-				printf ""
-			elif [[ $ver = $remotever ]]
-			then
-				echo "${bold}Warning:${normal} $key-$ver is allready on $remotever -- reinstalling"
-			else
-				if [[ $(echo -e "$ver\n$remotever" | sort | xargs | awk {'print $1'}) = $ver ]]
 				then
-					echo "Info: $key-$ver will be updated to $remotever!"
+					printf ""
+				elif [[ $ver = $remotever ]]
+				then
+					echo "${bold}Warning:${normal} $key-$ver is allready on $remotever -- reinstalling"
 				else
-					echo "${bold}Warning:${normal} $key-$ver is higher than AUR $remotever!"
+					if [[ $(echo -e "$ver\n$remotever" | sort | xargs | awk {'print $1'}) = $ver ]]
+					then
+						echo "Info: $key-$ver will be updated to $remotever!"
+					else
+						echo "${bold}Warning:${normal} $key-$ver is higher than AUR $remotever!"
+					fi
 				fi
 			fi
 			if [[ $(echo $res | cut -d'"' -f41) != :null, ]]
@@ -217,6 +231,22 @@ realinst(){
 		fi
 		mkdir -p ~/.cache/buildaur/build
 		cd ~/.cache/buildaur/build
+		if [[ $mode = url ]]
+		then
+			find ./urlbuild/buildaur.lock >/dev/null 2>/dev/null
+			if [[ $? = 0 ]]
+			then
+				echo ":: ${red}${bold}ERROR:${normal} Buildaur is currendly working in this directory! Finnish the process or remove $(pwd)/urlbuild/buildaur.lock!"
+				exit 1
+			fi
+		else
+			find ./$1/buildaur.lock >/dev/null 2>/dev/null
+			if [[ $? = 0 ]]
+			then
+				echo ":: ${red}${bold}ERROR:${normal} Buildaur is currendly working in this directory! Finnish the process or remove $(pwd)/$1/buildaur.lock!"
+				exit 1
+			fi
+		fi
 		rm -rf  ~/.cache/buildaur/build/$1
 		rm -rf  ~/.cache/buildaur/build/urlbuild
 		if [[ $mode = asp ]]
@@ -240,6 +270,7 @@ realinst(){
 				cd ~/.cache/buildaur/build/$1
 			fi
 		fi
+		touch ./buildaur.lock
 		if [[ $ask = "--noconfirm" ]]
 		then
 			ans=n
@@ -296,6 +327,7 @@ realinst(){
 			echo ":: ${red}${bold}ERROR:${normal} Package installation FAILED!"
 			errorcount=$(expr $errorcount + 1)
 		fi
+		rm ./buildaur.lock
 		shift
 		installcount=$(expr $installcount + 1)
 	done
@@ -311,6 +343,7 @@ update(){
 		res=${res}"&arg[]="${pkgnames[$counter]}
 		((counter++))
 	done
+	echo ":: Downloading packagelist..."
 	res=$(curl -s $res)
 	resultcount=$(echo $res | cut -d'"' -f9 | sed -e 's/://g' | sed -e 's/,//g')
 	willinst=()
@@ -355,8 +388,22 @@ update(){
 				willinst=(${willinst[@]} $name)
 			fi
 		fi
+		aurpacs[$count]=$name
 		((count++))
     ((counter++))
+	done
+	echo
+	echo ":: Searching non AUR packages..."
+	localpacs=($(echo ${aurpacs[@]} $(pacman -Qqm) | tr ' ' '\n' | sort | uniq -u))
+	echo "  ${#localpacs[*]} packages are not installed from any repository"
+	counter=0
+	count=1
+	echo ":: Listing them..."
+	while [[ $counter -lt ${#localpacs[*]} ]]
+	do
+		echo "($count/${#localpacs[*]}) $(pacman -Q ${localpacs[$counter]})"
+		((count++))
+		((counter++))
 	done
 	echo ""
 	install ${willinst[@]}
@@ -575,13 +622,14 @@ case $1 in
 		exit 0
 	;;
 	-Q)
-		if [[ $2 = "" ]]
+		shift
+		if [[ $1 = "" ]]
 		then
 			echo ":: Checking installed AUR packages..."
 			echo "  $(pacman -Qqm | wc -l) packages are curently installed from the AUR!"
 			echo ":: Giving out package infos..."
 			all=true
-			info -t $(pacman -Qqm)
+			info $(pacman -Qqm)
 		else
 			info $@
 		fi
